@startuml
|User|
start
:Відкрити сторінку бронювання;
:Обрати фільм, дату,\nсеанс і місця;
--> "Передати вибір до системи";

|TicketBookingSystem|
:Отримати вибір користувача;
:Перевірити наявність місць;

if (Місця доступні?) then (так)
  :Створити попереднє бронювання;
  :Надіслати користувачу\nдеталі для оплати;
else (ні)
  :Показати помилку:\nмісця недоступні;
  stop
endif

|User|
:Ввести платіжні дані;
--> "Відправити до PaymentService";

|PaymentService|
:Створити транзакцію;
:Перевірити платіжні дані;

if (Платіж успішний?) then (так)
  :Помітити транзакцію як Success;
else (ні)
  :Показати помилку оплати;
  stop
endif

|TicketBookingSystem|
:Підтвердити бронювання\nу CinemaSystem;

|CinemaSystem|
:Зареєструвати бронювання;
:Згенерувати електронний квиток;

|TicketBookingSystem|
:Отримати електронний квиток;

|User|
:Показати підтвердження покупки;
:Надати електронний квиток;
stop
@enduml